version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: express-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: databasenodejs
      POSTGRES_USER: ekaphop
      POSTGRES_PASSWORD: bb1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ekaphop -d databasenodejs"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Express Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: databasenodejs
      DB_USER: ekaphop
      DB_PASSWORD: bb1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./public:/usr/src/app/public:ro

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
